### ISSUE TITLE
Cursor clicking in edit box is broken.

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#193] opened 2016-07-26 15:21 UTC
Clicking to place your cursor in edit box does not always work. It seems to work with a pre-filled edit box (eg, your player name). An empty edit box which is typed in will always have the cursor placement problem.

**Comment by gajop** [comment] 2016-07-26 15:22
yep, essentially a duplicate of https://github.com/Spring-Chobby/Chobby/issues/183 : working on it

**Closed** 2016-07-27 16:14 UTC
Labels: minor bug, User Interface
