### ISSUE TITLE
Possibly only use one process

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#222] opened 2016-07-29 07:10 UTC
The idea here is to use Spring.Reload and a lua state that survives Spring.Reload. This would make Chobby work similarly to Dota 2. hokomoko likes this idea and would possibly implement the engine side.

**Comment by gajop** [comment] 2016-07-29 07:17
Duplicate of https://github.com/Spring-Chobby/Chobby/issues/99

**Closed by gajop** 2016-07-29 07:17 UTC
Labels: Discussion, duplicate, Engine
