### ISSUE TITLE
Black screen upon launch

### ISSUE THREAD

**Issue by ForbodingAngel** [Spring-Chobby/Chobby#476] opened 2019-07-29 06:35 UTC
An old bug. Usually fixed by deleting springsettings. Sometimes that doesn't work.

[infolog (2).txt](https://github.com/Spring-Chobby/Chobby/files/3440545/infolog.2.txt)

[https://cdn.discordapp.com/attachments/320919106171830274/605239790937571347/Screenshot_20190728-202625.jpg](url)

**Comment by gajop** [comment] 2019-07-30 14:56
I cannot reproduce this and I don't see where the error is. Right now I think this is the case of some bad gameConfig leading to config corruption, but I'm not sure yet as I can't reproduce it.

Can you delete the entire `C:\Users\WINDOWS\AppData\Roaming\Evolution RTS` folder and try again? In particular, start the lobby, try to login and enter a battle, then close it and upload an infolog (even if there's no blank screen issue). Check that infolog for any errors. Do this a few times if necessary until there are some errors.. 

PS: Ignore springsettings.cfg, it's not likely to be a culprit.

**Comment by ForbodingAngel** [comment] 2019-07-31 09:29
> PS: Ignore springsettings.cfg, it's not likely to be a culprit.

We have a years worth of spring troubleshooting this exact issue that says otherwise. Perhaps not the only issue, but certainly in many cases deleting it fixes the issue.

> Can you delete the entire C:\Users\WINDOWS\AppData\Roaming\Evolution RTS folder and try again? In particular, start the lobby, try to login and enter a battle, then close it and upload an infolog (even if there's no blank screen issue). Check that infolog for any errors. Do this a few times if necessary until there are some errors..

He did. He deleted everything and reinstalled multiple times. Perhaps you should ping him in discord and talk with him directly.

**Comment by gajop** [comment] 2019-08-03 11:38
In my talks with Damgam we've deduced that this issue is only occurring with an old version of the launcher (different repo), and that this is an installation issue. (Who knows what was downloaded...) 

So closing. If this happens again (with a new launcher, from the mutator repo), please open a new issue.

**Closed by gajop** 2019-08-03 11:38 UTC
