### ISSUE TITLE
Open URLs with default browser

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#139] opened 2016-07-14 15:30 UTC
Spring needs to be able to tell the OS to open a URL. This is required for many community integration features (streams, download maps/replays, wiki link etc..) as well as chat.

**Comment by gajop** [comment] 2016-07-14 15:31
duplicate of https://github.com/Spring-Chobby/Chobby/issues/89

**Closed by gajop** 2016-07-14 15:31 UTC
Labels: Discussion, duplicate, Engine, Feature, LibLobby
