### ISSUE TITLE
Chobby doesn't handle large modoption categories well

### ISSUE THREAD

**Issue by ForbodingAngel** [Spring-Chobby/Chobby#430] opened 2017-11-16 12:52 UTC
Currently this happens:
![image](https://i.imgur.com/hJzarox.jpg)

As an example of what should be happening:
![image](https://user-images.githubusercontent.com/369586/32892068-e02ad2b2-ca89-11e7-9f59-6032c92658c7.png)

Modoptions are of rather critical importance in evo, and they are used very often, so this is near and dear to my heart :-)

**Comment by gajop** [comment] 2017-11-16 13:06
Duplicate of https://github.com/Spring-Chobby/Chobby/issues/419

**Closed by gajop** 2017-11-16 13:06 UTC
